#!/bin/bash

DEVICE=rolex
TG_USERNAME=@adi153
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch lineage_rolex-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

# Telgram env setup
export BOT_MSG_URL="https://api.telegram.org/bot$API_BOT/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$API_BOT/sendDocument"

tg_post_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
        -d "parse_mode=html" \
        -d text="$1"
}

tg_error_msg() {
        curl -s -X POST "$BOT_MSG_URL" -d chat_id="$2" \
        -d "parse_mode=html" \
        -d text="$1" \
        -d log_file="$3"
}

# stuffs
up(){
	curl --upload-file $1 https://transfer.sh/
}


tg_send_file() {
	curl -F chat_id=$CHATID -F document=@${1} -F parse_mode=markdown $BOT_BUILD_URL
}

make_rom(){
	tg_post_msg "<b>Cooking of CrDroid has been started in adi's kitchen for Rolex/Riva</b>" "$CHATID"
	mka bacon -j16 | tee logs.log
	if [ -f out/target/product/$DEVICE/*zip ]; then
	    cd out/target/product/$DEVICE
		zip=$(rclone copy *zip Drive:ROM)
		zfile=$(ls *zip)
		echo " "
		tg_post_msg "<b>$TG_USERNAME Build Completed</b>%0A%0A<b>Name : </b> <code>"$zfile"</code>" "$CHATID"
	else
		LOGS=$(up logs.log)
		tg_post_msg "<b>OMG! Build failed, $TG_USERNAME fix it fast</b>" "$CHATID"
		tg_send_file logs.log
	fi
}

# Finally
make_rom
