#!/bin/bash

MANIFEST=https://github.com/LineageOS/android.git
BRANCH=lineage-18.1
DEVICE=rolex
BRAND=xiaomi
PLATFORM=msm8917
DT_LINK=https://github.com/Thagoo/android_device_xiaomi_rolex.git
VT_LINK=https://github.com/Thagoo/android_vendor_xiaomi_rolex.git
KT_LINK=https://github.com/Thagoo/platform_kernel_xiaomi_msm8917.git

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault

git config --global user.name adi153
git config --global user.email singhmanohar6699@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone $DT_LINK --depth=1 --single-branch -b 11 device/$BRAND/$DEVICE
git clone $VT_LINK --depth=1 --single-branch -b r vendor/$BRAND/$DEVICE
git clone $KT_LINK --depth=1 --single-branch -b lineage-18.1 kernel/$BRAND/$PLATFORM
